trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Self-Hosted-Pavan
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
        name: Self-Hosted-Pavan
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure subscription (***)'
          appType: 'webAppLinux'
          WebAppName: 'spavanra97'
          packageForLinux: '$(System.ArtifactsDirectory)/drop'
          RuntimeStack: 'STATICSITE|1.0'